version: '3.9'

services:
  authorizer:
    container_name: authorizerapp
    image: authorizer/authorizerapp:latest
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: jdbc:postgresql://db:5432/postgres
        PG_USER: postgres
        PG_PASSWORD: postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
